from detectron2.config import CfgNode as CN
from projects.CenterNet.centernet import add_centernet_config


def add_fairmot_config(cfg: CN):
    _C = cfg
    add_centernet_config(_C)

    # -----------------------------------------------------------------------------
    # Tracking for non-E2E model
    # -----------------------------------------------------------------------------
    _C.MODEL.DETECTOR = CN({"ENABLED": True})
    _C.MODEL.DETECTOR.META_ARCHITECTURE = "CenterNet"
    _C.MODEL.DETECTOR.WEIGHTS = ""

    _C.MODEL.TRACKER = CN({"ENABLED": True})
    _C.MODEL.TRACKER.META_ARCHITECTURE = "JDETracker"
    _C.MODEL.TRACKER.WEIGHTS = ""
    _C.MODEL.TRACKER.TOPK_FLAG = False
    _C.MODEL.TRACKER.TOPK = 100

    _C.MODEL.TRACKER.JDE = CN()
    _C.MODEL.TRACKER.JDE.MIN_BOX_AREA = 100
    _C.MODEL.TRACKER.JDE.TRACK_BUFFER = 30
    _C.MODEL.TRACKER.JDE.DET_THRES = 0.4
    _C.MODEL.TRACKER.JDE.INIT_TRACK_DET_THRES = 0.5
    _C.MODEL.TRACKER.JDE.RECOVERY_FLAG = False
    _C.MODEL.TRACKER.JDE.RECOVERY_THRESH = 0.9
    _C.MODEL.TRACKER.JDE.RECOVERY_LOW_DET_THRESH = 0.4
    _C.MODEL.TRACKER.JDE.KALMAN_FILTER_FLAG = True
    _C.MODEL.TRACKER.JDE.FUSE_MOTION_FLAG = True
    _C.MODEL.TRACKER.JDE.FEATURE_SMOOTH_FLAG = True
    _C.MODEL.TRACKER.JDE.FEATURE_SMOOTH_BY_SCORE = False
    _C.MODEL.TRACKER.JDE.FIRST_MATCH_THRES = 0.4
    _C.MODEL.TRACKER.JDE.SECOND_MATCH_THRES = 0.5

    _C.MODEL.TRACKER.BYTETRACK = CN()
    _C.MODEL.TRACKER.BYTETRACK.MIN_BOX_AREA = 100
    _C.MODEL.TRACKER.BYTETRACK.TRACK_BUFFER = 30
    _C.MODEL.TRACKER.BYTETRACK.DET_THRES = 0.4
    _C.MODEL.TRACKER.BYTETRACK.LOW_DET_THRES = 0.2
    _C.MODEL.TRACKER.BYTETRACK.INIT_TRACK_DET_THRES = 0.5
    _C.MODEL.TRACKER.BYTETRACK.FIRST_MATCH_THRES = 0.4
    _C.MODEL.TRACKER.BYTETRACK.SECOND_MATCH_THRES = 0.5
    _C.MODEL.TRACKER.BYTETRACK.LOW_MATCH_THRES = 0.4
    _C.MODEL.TRACKER.BYTETRACK.KALMAN_FILTER_FLAG = True
    _C.MODEL.TRACKER.BYTETRACK.FUSE_MOTION_FLAG = True
    _C.MODEL.TRACKER.BYTETRACK.FEATURE_SMOOTH_FLAG = True
    _C.MODEL.TRACKER.BYTETRACK.FEATURE_SMOOTH_BY_SCORE = False
