MODEL:
  META_ARCHITECTURE: "FairMOT"
  MASK_ON: False
  PIXEL_MEAN: [0.408, 0.447, 0.470]
  PIXEL_STD: [0.289, 0.274, 0.278]
  DETECTOR:
    ENABLED: True
    META_ARCHITECTURE: "CenterNet"
  BACKBONE:
    NAME: "DLA"
  CENTERNET:
    UPSAMPLE_LAYER:
      NAME: "DLASegUp"
    NUM_CLASSES: 1
    HEAD:
      REID_DIM: 128
    OUTPUT_SIZE: (608, 1088)
    HM_SIZE: (152, 272)
    INPUT_ALIGN: False
    TLBR_FLAG: True
    MAX_PER_IMAGE: 500
  IDENTITY_ON: True
  LOSS:
    AUTO_WEIGHT_FLAG: True
    ## fixed weights for each loss when auto_weight = False
    DET_WEIGHT: 1.0
    ID_WEIGHT: 0.1
TEST:
  EVAL_DETECTION: True
  EVAL_TRACKING: True
  EVAL_FILTER_DET_FLAG: True
  EVAL_DET_BY_SEQ_FLAG: False
DATALOADER:
  REASSIGN_ID: True
  ASPECT_RATIO_GROUPING: False
  FILTER_EMPTY_ANNOTATIONS: True
  SAMPLER_TEST: "SeqInferenceSampler"
VERSION: 2