MODEL:
  META_ARCHITECTURE: "CenterNet"
  MASK_ON: False
  PIXEL_MEAN: [0.408, 0.447, 0.470]
  PIXEL_STD: [0.289, 0.274, 0.278]
  CENTERNET:
    OUTPUT_SIZE: (512, 512)
    HM_SIZE: (128, 128)
    AFFINE:
      BORDER: 128
    TLBR_FLAG: False
DATASETS:
  TRAIN: ("nfs_coco_2017_train",)
  TEST: ("nfs_coco_2017_val",)
SOLVER:
  OPTIMIZER: "Adam"
  IMS_PER_BATCH: 128
  BASE_LR: 0.0005
  STEPS: (90, 120)
  WARMUP_ITERS: 0
  MAX_EPOCH: 140
TEST:
  EVAL_PERIOD: 1
INPUT:
  FORMAT: "BGR"
  NORM_BY_MEAN_STD_FLAG: True
VERSION: 2
