_BASE_: "../Base-FairMOT.yaml"
MODEL:
  DETECTOR:
    WEIGHTS: "centernet_dla34_coco.pth"
  CENTERNET:
    INFERENCE_GT: False
  TRACKER:
    ENABLED: True
    META_ARCHITECTURE: "JDETracker"
#    META_ARCHITECTURE: "BYTETracker"
    TOPK_FLAG: False
    TOPK: 30
    JDE:
      DET_THRES: 0.4
      INIT_TRACK_DET_THRES: 0.5
      FEATURE_SMOOTH_BY_SCORE: False
    BYTETRACK:
      DET_THRES: 0.4
      LOW_DET_THRES: 0.2
      INIT_TRACK_DET_THRES: 0.5
      LOW_MATCH_THRES: 0.4
      FIRST_MATCH_THRES: 0.4
      FEATURE_SMOOTH_BY_SCORE: True
SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0
  STEPS: (50,)
  MAX_EPOCH: 60
#  STEPS: (20, )
#  MAX_EPOCH: 30
  WARMUP_ITERS: 0
  CHECKPOINT_PERIOD: 30
TEST:
  EVAL_PERIOD: 5
  EVAL_FILTER_DET_SCORE_THRESH: 0.5
#  EVAL_FILTER_DET_SCORE_THRESH: 0.4
  EVAL_MIN_VISIBILITY: 0.0
DATASETS:
  TRAIN: ("mix_mot17_sub_train", "mix_crowdhuman_train",)
  TEST: ("mot17_sub_val",)
INPUT:
  CLIP_BY_IMAGE: False # mot17
  NORM_BY_MEAN_STD_FLAG: True
  FORMAT: 'BGR'
  FILTER_OUT_IMAGE: False
  TRAIN_MIN_VISIBILITY: 0.0

